spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/twowheelmadness
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_schema: public


